/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matchmakerfinal;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Stephanie
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        setSize(1016, 699);
        calcResults.setOpaque(false);
        calcResults.setContentAreaFilled(false);
        calcResults.setBorderPainted(false);
        File f = new File ("SID.txt");        
        numOfUsers.setText(String.valueOf(findLength(f)));
        File x = new File ("GeneralInfo.txt");
        numOfSubmits.setText(String.valueOf(findLength(x)));
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcResults = new javax.swing.JButton();
        numOfUsers = new javax.swing.JTextField();
        numOfSubmits = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        calcResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcResultsActionPerformed(evt);
            }
        });
        getContentPane().add(calcResults);
        calcResults.setBounds(720, 500, 320, 100);

        numOfUsers.setEditable(false);
        numOfUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOfUsersActionPerformed(evt);
            }
        });
        getContentPane().add(numOfUsers);
        numOfUsers.setBounds(640, 330, 230, 30);

        numOfSubmits.setEditable(false);
        getContentPane().add(numOfSubmits);
        numOfSubmits.setBounds(640, 420, 230, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchmakerfinal/Admin.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1148, 711);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numOfUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOfUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numOfUsersActionPerformed

    private void calcResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcResultsActionPerformed
         PrintWriter pw = null;         
            try {
                 // The file to indicate wether the admin has decided to calculate the results
                File f = new File("readyToCalc.txt");
                // create a PrintWriter that will append the file (will add to it as apppose to overwrite)
                pw = new PrintWriter(new FileWriter(f, true));               
                pw.println("calculate");                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                // close the print writer
                pw.close();  
        
        }
              setVisible(false);
             new LogIn().setVisible(true);  
    }//GEN-LAST:event_calcResultsActionPerformed

    private int findLength(File x){
        // create an int var to store the length of the file
        int length = 0;
        Scanner s = null;
        try {            
            s = new Scanner (x);
            // While you have not reached the end of the file
            while (s.hasNextLine()){
            // move to next line
            s.nextLine();
            // increase length by 1
            length++;
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(General.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(General.class.getName()).log(Level.SEVERE, null, ex);
    }
        // return length of the file
        return length;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcResults;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField numOfSubmits;
    private javax.swing.JTextField numOfUsers;
    // End of variables declaration//GEN-END:variables
}
