/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matchmakerfinal;

/**
 *
 * @author Braedon
 */
public class AppearanceQuiz extends javax.swing.JFrame {
int bodyTypePref;
int bodyTypePersonal;
int hairColPref;
int hairColPersonal;
int heightPref;
int heightPersonal;
int backgroundPersonal;
int backgroundPref;
int eyeColPersonal;
int eyeColPref;


    /**
     * Creates new form AppearanceQuiz
     */
    public AppearanceQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyType1 = new javax.swing.JButton();
        bodyType2 = new javax.swing.JButton();
        bodyType3 = new javax.swing.JButton();
        bodyType4 = new javax.swing.JButton();
        bodyType5 = new javax.swing.JButton();
        Height2 = new javax.swing.JButton();
        Height1 = new javax.swing.JButton();
        Height5 = new javax.swing.JButton();
        Height4 = new javax.swing.JButton();
        Height3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bodyType1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyType1.setText("Body type 1");
        bodyType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyType1ActionPerformed(evt);
            }
        });

        bodyType2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyType2.setText("Body type 2");
        bodyType2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyType2ActionPerformed(evt);
            }
        });

        bodyType3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyType3.setText("Body type 3");
        bodyType3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyType3ActionPerformed(evt);
            }
        });

        bodyType4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyType4.setText("Body type 4");
        bodyType4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyType4ActionPerformed(evt);
            }
        });

        bodyType5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyType5.setText("Body type 5");
        bodyType5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyType5ActionPerformed(evt);
            }
        });

        Height2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        Height2.setText("Height 2");
        Height2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Height2ActionPerformed(evt);
            }
        });

        Height1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        Height1.setText("Height 1");
        Height1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Height1ActionPerformed(evt);
            }
        });

        Height5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        Height5.setText("Height 4");
        Height5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Height5ActionPerformed(evt);
            }
        });

        Height4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        Height4.setText("Height 4");
        Height4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Height4ActionPerformed(evt);
            }
        });

        Height3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        Height3.setText("Height 3");
        Height3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Height3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bodyType1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bodyType2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bodyType3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bodyType4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bodyType5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Height1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Height2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Height3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Height4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Height5)))
                .addContainerGap(391, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodyType1)
                    .addComponent(bodyType2)
                    .addComponent(bodyType3)
                    .addComponent(bodyType4)
                    .addComponent(bodyType5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Height1)
                    .addComponent(Height2)
                    .addComponent(Height3)
                    .addComponent(Height4)
                    .addComponent(Height5))
                .addContainerGap(460, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bodyType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyType1ActionPerformed
    bodyTypePersonal = 1;
    }//GEN-LAST:event_bodyType1ActionPerformed

    private void bodyType4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyType4ActionPerformed
    bodyTypePersonal = 4;
    }//GEN-LAST:event_bodyType4ActionPerformed

    private void bodyType2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyType2ActionPerformed
    bodyTypePersonal = 2;
    }//GEN-LAST:event_bodyType2ActionPerformed

    private void bodyType3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyType3ActionPerformed
    bodyTypePersonal = 3;
    }//GEN-LAST:event_bodyType3ActionPerformed

    private void bodyType5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyType5ActionPerformed
    bodyTypePersonal = 5;
    }//GEN-LAST:event_bodyType5ActionPerformed

    private void Height2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Height2ActionPerformed
    heightPersonal = 2;
    }//GEN-LAST:event_Height2ActionPerformed

    private void Height1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Height1ActionPerformed
    heightPersonal = 1;
    }//GEN-LAST:event_Height1ActionPerformed

    private void Height5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Height5ActionPerformed
    heightPersonal = 5;
    }//GEN-LAST:event_Height5ActionPerformed

    private void Height4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Height4ActionPerformed
    heightPersonal = 4;
    }//GEN-LAST:event_Height4ActionPerformed

    private void Height3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Height3ActionPerformed
    heightPersonal = 3;
    }//GEN-LAST:event_Height3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppearanceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppearanceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppearanceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppearanceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppearanceQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Height1;
    private javax.swing.JButton Height2;
    private javax.swing.JButton Height3;
    private javax.swing.JButton Height4;
    private javax.swing.JButton Height5;
    private javax.swing.JButton bodyType1;
    private javax.swing.JButton bodyType2;
    private javax.swing.JButton bodyType3;
    private javax.swing.JButton bodyType4;
    private javax.swing.JButton bodyType5;
    // End of variables declaration//GEN-END:variables
}
