/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matchmakerfinal;

import javax.swing.JOptionPane;

/**
 *
 * @author Braedon
 */
public class AppearanceQuiz extends javax.swing.JFrame {

    int bodyTypePref;
    int bodyTypePersonal;
    int hairColPref;
    int hairColPersonal;
    int heightPref;
    int heightPersonal;
    int backgroundPersonal;
    int backgroundPref;
    int bodyWeightPersonal;
    int bodyWeightPref;

    /**
     * Creates new form AppearanceQuiz
     */
    public AppearanceQuiz() {
        initComponents();
        setSize(1108, 733);
//        bodyType1.setOpaque(false);
//        bodyType1.setContentAreaFilled(false);
//        bodyType1.setBorderPainted(true);
//        bodyType2.setOpaque(false);
//        bodyType2.setContentAreaFilled(false);
//        bodyType2.setBorderPainted(false);
//        bodyType3.setOpaque(false);
//        bodyType3.setContentAreaFilled(false);
//        bodyType3.setBorderPainted(false);
//        bodyType4.setOpaque(false);
//        bodyType4.setContentAreaFilled(false);
//        bodyType4.setBorderPainted(false);
//        bodyType5.setOpaque(false);
//        bodyType5.setContentAreaFilled(false);
//        bodyType5.setBorderPainted(false);
//        
//        Height1.setOpaque(false);
//        Height1.setContentAreaFilled(false);
//        Height1.setBorderPainted(false);        
//        Height2.setOpaque(false);
//        Height2.setContentAreaFilled(false);
//        Height2.setBorderPainted(false);        
//        Height3.setOpaque(false);
//        Height3.setContentAreaFilled(false);
//        Height3.setBorderPainted(false);        
//        Height4.setOpaque(false);
//        Height4.setContentAreaFilled(false);
//        Height4.setBorderPainted(false);        
//        Height5.setOpaque(false);
//        Height5.setContentAreaFilled(false);
//        Height5.setBorderPainted(false);
//        
//        hairColourPersonal1.setOpaque(false);
//        hairColourPersonal1.setContentAreaFilled(false);
//        hairColourPersonal1.setBorderPainted(false);        
//        hairColourPersonal2.setOpaque(false);
//        hairColourPersonal2.setContentAreaFilled(false);
//        hairColourPersonal2.setBorderPainted(false);
//        hairColourPersonal3.setOpaque(false);
//        hairColourPersonal3.setContentAreaFilled(false);
//        hairColourPersonal3.setBorderPainted(false);
//        hairColourPersonal4.setOpaque(false);
//        hairColourPersonal4.setContentAreaFilled(false);
//        hairColourPersonal4.setBorderPainted(false);
//        hairColourPersonal5.setOpaque(false);
//        hairColourPersonal5.setContentAreaFilled(false);
//        hairColourPersonal5.setBorderPainted(false);
        
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyTypePersonal1 = new javax.swing.JButton();
        bodyTypePersonal2 = new javax.swing.JButton();
        bodyTypePersonal3 = new javax.swing.JButton();
        bodyTypePersonal4 = new javax.swing.JButton();
        bodyTypePersonal5 = new javax.swing.JButton();
        HeightPersonal2 = new javax.swing.JButton();
        HeightPersonal1 = new javax.swing.JButton();
        HeightPersonal5 = new javax.swing.JButton();
        HeightPersonal4 = new javax.swing.JButton();
        HeightPersonal3 = new javax.swing.JButton();
        hairColourPersonal5 = new javax.swing.JButton();
        hairColourPersonal4 = new javax.swing.JButton();
        hairColourPersonal2 = new javax.swing.JButton();
        hairColourPersonal1 = new javax.swing.JButton();
        hairColourPersonal3 = new javax.swing.JButton();
        backgroundPersonal5 = new javax.swing.JButton();
        backgroundPersonal4 = new javax.swing.JButton();
        backgroundPersonal2 = new javax.swing.JButton();
        backgroundPersonal1 = new javax.swing.JButton();
        backgroundPersonal3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bodyWeightPersonal5 = new javax.swing.JButton();
        bodyWeightPersonal4 = new javax.swing.JButton();
        bodyWeightPersonal2 = new javax.swing.JButton();
        bodyWeightPersonal1 = new javax.swing.JButton();
        bodyWeightPersonal3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Finished = new javax.swing.JButton();
        backgroundPref5 = new javax.swing.JButton();
        hairColourPref3 = new javax.swing.JButton();
        hairColourPref1 = new javax.swing.JButton();
        hairColourPref2 = new javax.swing.JButton();
        hairColourPref4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        backgroundPref1 = new javax.swing.JButton();
        backgroundPref3 = new javax.swing.JButton();
        backgroundPref4 = new javax.swing.JButton();
        backgroundPref2 = new javax.swing.JButton();
        HeightPref2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        bodyTypePref5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        bodyWeightPref5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        bodyTypePref2 = new javax.swing.JButton();
        bodyTypePref1 = new javax.swing.JButton();
        bodyTypePref4 = new javax.swing.JButton();
        bodyTypePref3 = new javax.swing.JButton();
        HeightPref5 = new javax.swing.JButton();
        bodyWeightPref4 = new javax.swing.JButton();
        HeightPref4 = new javax.swing.JButton();
        bodyWeightPref2 = new javax.swing.JButton();
        HeightPref3 = new javax.swing.JButton();
        bodyWeightPref1 = new javax.swing.JButton();
        hairColourPref5 = new javax.swing.JButton();
        bodyWeightPref3 = new javax.swing.JButton();
        HeightPref1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1108, 733));
        setResizable(false);

        bodyTypePersonal1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyTypePersonal1.setText("Body type 1");
        bodyTypePersonal1.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyTypePersonal1.setRequestFocusEnabled(false);
        bodyTypePersonal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyTypePersonal1ActionPerformed(evt);
            }
        });

        bodyTypePersonal2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyTypePersonal2.setText("Body type 2");
        bodyTypePersonal2.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyTypePersonal2.setRequestFocusEnabled(false);
        bodyTypePersonal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyTypePersonal2ActionPerformed(evt);
            }
        });

        bodyTypePersonal3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyTypePersonal3.setText("Body type 3");
        bodyTypePersonal3.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyTypePersonal3.setRequestFocusEnabled(false);
        bodyTypePersonal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyTypePersonal3ActionPerformed(evt);
            }
        });

        bodyTypePersonal4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyTypePersonal4.setText("Body type 4");
        bodyTypePersonal4.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyTypePersonal4.setRequestFocusEnabled(false);
        bodyTypePersonal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyTypePersonal4ActionPerformed(evt);
            }
        });

        bodyTypePersonal5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyTypePersonal5.setText("Body type 5");
        bodyTypePersonal5.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyTypePersonal5.setRequestFocusEnabled(false);
        bodyTypePersonal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyTypePersonal5ActionPerformed(evt);
            }
        });

        HeightPersonal2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        HeightPersonal2.setText("Height 2");
        HeightPersonal2.setPreferredSize(new java.awt.Dimension(100, 25));
        HeightPersonal2.setRequestFocusEnabled(false);
        HeightPersonal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightPersonal2ActionPerformed(evt);
            }
        });

        HeightPersonal1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        HeightPersonal1.setText("Height 1");
        HeightPersonal1.setPreferredSize(new java.awt.Dimension(100, 25));
        HeightPersonal1.setRequestFocusEnabled(false);
        HeightPersonal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightPersonal1ActionPerformed(evt);
            }
        });

        HeightPersonal5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        HeightPersonal5.setText("Height 4");
        HeightPersonal5.setPreferredSize(new java.awt.Dimension(100, 25));
        HeightPersonal5.setRequestFocusEnabled(false);
        HeightPersonal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightPersonal5ActionPerformed(evt);
            }
        });

        HeightPersonal4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        HeightPersonal4.setText("Height 4");
        HeightPersonal4.setPreferredSize(new java.awt.Dimension(100, 25));
        HeightPersonal4.setRequestFocusEnabled(false);
        HeightPersonal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightPersonal4ActionPerformed(evt);
            }
        });

        HeightPersonal3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        HeightPersonal3.setText("Height 3");
        HeightPersonal3.setPreferredSize(new java.awt.Dimension(100, 25));
        HeightPersonal3.setRequestFocusEnabled(false);
        HeightPersonal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightPersonal3ActionPerformed(evt);
            }
        });

        hairColourPersonal5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        hairColourPersonal5.setText("Hair Colour 5");
        hairColourPersonal5.setPreferredSize(new java.awt.Dimension(100, 25));
        hairColourPersonal5.setRequestFocusEnabled(false);
        hairColourPersonal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairColourPersonal5ActionPerformed(evt);
            }
        });

        hairColourPersonal4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        hairColourPersonal4.setText("Hair Colour 4");
        hairColourPersonal4.setPreferredSize(new java.awt.Dimension(100, 25));
        hairColourPersonal4.setRequestFocusEnabled(false);
        hairColourPersonal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairColourPersonal4ActionPerformed(evt);
            }
        });

        hairColourPersonal2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        hairColourPersonal2.setText("Hair Colour 2");
        hairColourPersonal2.setPreferredSize(new java.awt.Dimension(100, 25));
        hairColourPersonal2.setRequestFocusEnabled(false);
        hairColourPersonal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairColourPersonal2ActionPerformed(evt);
            }
        });

        hairColourPersonal1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        hairColourPersonal1.setText("Hair Colour 1");
        hairColourPersonal1.setPreferredSize(new java.awt.Dimension(100, 25));
        hairColourPersonal1.setRequestFocusEnabled(false);
        hairColourPersonal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairColourPersonal1ActionPerformed(evt);
            }
        });

        hairColourPersonal3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        hairColourPersonal3.setText("Hair Colour 3");
        hairColourPersonal3.setPreferredSize(new java.awt.Dimension(100, 25));
        hairColourPersonal3.setRequestFocusEnabled(false);
        hairColourPersonal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairColourPersonal3ActionPerformed(evt);
            }
        });

        backgroundPersonal5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        backgroundPersonal5.setText("Background 5");
        backgroundPersonal5.setPreferredSize(new java.awt.Dimension(100, 25));
        backgroundPersonal5.setRequestFocusEnabled(false);
        backgroundPersonal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundPersonal5ActionPerformed(evt);
            }
        });

        backgroundPersonal4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        backgroundPersonal4.setText("Background 4");
        backgroundPersonal4.setPreferredSize(new java.awt.Dimension(100, 25));
        backgroundPersonal4.setRequestFocusEnabled(false);
        backgroundPersonal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundPersonal4ActionPerformed(evt);
            }
        });

        backgroundPersonal2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        backgroundPersonal2.setText("Background 2");
        backgroundPersonal2.setPreferredSize(new java.awt.Dimension(100, 25));
        backgroundPersonal2.setRequestFocusEnabled(false);
        backgroundPersonal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundPersonal2ActionPerformed(evt);
            }
        });

        backgroundPersonal1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        backgroundPersonal1.setText("Background 1");
        backgroundPersonal1.setPreferredSize(new java.awt.Dimension(100, 25));
        backgroundPersonal1.setRequestFocusEnabled(false);
        backgroundPersonal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundPersonal1ActionPerformed(evt);
            }
        });

        backgroundPersonal3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        backgroundPersonal3.setText("Background 3");
        backgroundPersonal3.setPreferredSize(new java.awt.Dimension(100, 25));
        backgroundPersonal3.setRequestFocusEnabled(false);
        backgroundPersonal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundPersonal3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Body Type?");

        jLabel2.setText("Height?");

        jLabel3.setText("Hair Colour?");

        jLabel4.setText("Background?");

        jLabel5.setText("Body Weight?");

        bodyWeightPersonal5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyWeightPersonal5.setText("Body Weight 5");
        bodyWeightPersonal5.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyWeightPersonal5.setRequestFocusEnabled(false);
        bodyWeightPersonal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyWeightPersonal5ActionPerformed(evt);
            }
        });

        bodyWeightPersonal4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyWeightPersonal4.setText("Body Weight 4");
        bodyWeightPersonal4.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyWeightPersonal4.setRequestFocusEnabled(false);
        bodyWeightPersonal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyWeightPersonal4ActionPerformed(evt);
            }
        });

        bodyWeightPersonal2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyWeightPersonal2.setText("Body Weight 2");
        bodyWeightPersonal2.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyWeightPersonal2.setRequestFocusEnabled(false);
        bodyWeightPersonal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyWeightPersonal2ActionPerformed(evt);
            }
        });

        bodyWeightPersonal1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyWeightPersonal1.setText("Body Weight 1");
        bodyWeightPersonal1.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyWeightPersonal1.setRequestFocusEnabled(false);
        bodyWeightPersonal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyWeightPersonal1ActionPerformed(evt);
            }
        });

        bodyWeightPersonal3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyWeightPersonal3.setText("Body Weight 3");
        bodyWeightPersonal3.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyWeightPersonal3.setRequestFocusEnabled(false);
        bodyWeightPersonal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyWeightPersonal3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Appearance Test");

        jLabel7.setText("_________________________________________________________________________________________________________");

        Finished.setText("Finished");
        Finished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishedActionPerformed(evt);
            }
        });

        backgroundPref5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        backgroundPref5.setText("Background 5");
        backgroundPref5.setPreferredSize(new java.awt.Dimension(100, 25));
        backgroundPref5.setRequestFocusEnabled(false);
        backgroundPref5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundPref5ActionPerformed(evt);
            }
        });

        hairColourPref3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        hairColourPref3.setText("Hair Colour 3");
        hairColourPref3.setPreferredSize(new java.awt.Dimension(100, 25));
        hairColourPref3.setRequestFocusEnabled(false);
        hairColourPref3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairColourPref3ActionPerformed(evt);
            }
        });

        hairColourPref1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        hairColourPref1.setText("Hair Colour 1");
        hairColourPref1.setPreferredSize(new java.awt.Dimension(100, 25));
        hairColourPref1.setRequestFocusEnabled(false);
        hairColourPref1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairColourPref1ActionPerformed(evt);
            }
        });

        hairColourPref2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        hairColourPref2.setText("Hair Colour 2");
        hairColourPref2.setPreferredSize(new java.awt.Dimension(100, 25));
        hairColourPref2.setRequestFocusEnabled(false);
        hairColourPref2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairColourPref2ActionPerformed(evt);
            }
        });

        hairColourPref4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        hairColourPref4.setText("Hair Colour 4");
        hairColourPref4.setPreferredSize(new java.awt.Dimension(100, 25));
        hairColourPref4.setRequestFocusEnabled(false);
        hairColourPref4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairColourPref4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Body Type?");

        jLabel9.setText("Height?");

        backgroundPref1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        backgroundPref1.setText("Background 1");
        backgroundPref1.setPreferredSize(new java.awt.Dimension(100, 25));
        backgroundPref1.setRequestFocusEnabled(false);
        backgroundPref1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundPref1ActionPerformed(evt);
            }
        });

        backgroundPref3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        backgroundPref3.setText("Background 3");
        backgroundPref3.setPreferredSize(new java.awt.Dimension(100, 25));
        backgroundPref3.setRequestFocusEnabled(false);
        backgroundPref3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundPref3ActionPerformed(evt);
            }
        });

        backgroundPref4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        backgroundPref4.setText("Background 4");
        backgroundPref4.setPreferredSize(new java.awt.Dimension(100, 25));
        backgroundPref4.setRequestFocusEnabled(false);
        backgroundPref4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundPref4ActionPerformed(evt);
            }
        });

        backgroundPref2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        backgroundPref2.setText("Background 2");
        backgroundPref2.setPreferredSize(new java.awt.Dimension(100, 25));
        backgroundPref2.setRequestFocusEnabled(false);
        backgroundPref2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundPref2ActionPerformed(evt);
            }
        });

        HeightPref2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        HeightPref2.setText("Height 2");
        HeightPref2.setPreferredSize(new java.awt.Dimension(100, 25));
        HeightPref2.setRequestFocusEnabled(false);
        HeightPref2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightPref2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Background?");

        bodyTypePref5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyTypePref5.setText("Body type 5");
        bodyTypePref5.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyTypePref5.setRequestFocusEnabled(false);
        bodyTypePref5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyTypePref5ActionPerformed(evt);
            }
        });

        jLabel11.setText("Hair Colour?");

        bodyWeightPref5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyWeightPref5.setText("Body Weight 5");
        bodyWeightPref5.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyWeightPref5.setRequestFocusEnabled(false);
        bodyWeightPref5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyWeightPref5ActionPerformed(evt);
            }
        });

        jLabel12.setText("Body Weight?");

        bodyTypePref2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyTypePref2.setText("Body type 2");
        bodyTypePref2.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyTypePref2.setRequestFocusEnabled(false);
        bodyTypePref2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyTypePref2ActionPerformed(evt);
            }
        });

        bodyTypePref1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyTypePref1.setText("Body type 1");
        bodyTypePref1.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyTypePref1.setRequestFocusEnabled(false);
        bodyTypePref1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyTypePref1ActionPerformed(evt);
            }
        });

        bodyTypePref4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyTypePref4.setText("Body type 4");
        bodyTypePref4.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyTypePref4.setRequestFocusEnabled(false);
        bodyTypePref4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyTypePref4ActionPerformed(evt);
            }
        });

        bodyTypePref3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyTypePref3.setText("Body type 3");
        bodyTypePref3.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyTypePref3.setRequestFocusEnabled(false);
        bodyTypePref3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyTypePref3ActionPerformed(evt);
            }
        });

        HeightPref5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        HeightPref5.setText("Height 4");
        HeightPref5.setPreferredSize(new java.awt.Dimension(100, 25));
        HeightPref5.setRequestFocusEnabled(false);
        HeightPref5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightPref5ActionPerformed(evt);
            }
        });

        bodyWeightPref4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyWeightPref4.setText("Body Weight 4");
        bodyWeightPref4.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyWeightPref4.setRequestFocusEnabled(false);
        bodyWeightPref4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyWeightPref4ActionPerformed(evt);
            }
        });

        HeightPref4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        HeightPref4.setText("Height 4");
        HeightPref4.setPreferredSize(new java.awt.Dimension(100, 25));
        HeightPref4.setRequestFocusEnabled(false);
        HeightPref4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightPref4ActionPerformed(evt);
            }
        });

        bodyWeightPref2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyWeightPref2.setText("Body Weight 2");
        bodyWeightPref2.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyWeightPref2.setRequestFocusEnabled(false);
        bodyWeightPref2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyWeightPref2ActionPerformed(evt);
            }
        });

        HeightPref3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        HeightPref3.setText("Height 3");
        HeightPref3.setPreferredSize(new java.awt.Dimension(100, 25));
        HeightPref3.setRequestFocusEnabled(false);
        HeightPref3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightPref3ActionPerformed(evt);
            }
        });

        bodyWeightPref1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyWeightPref1.setText("Body Weight 1");
        bodyWeightPref1.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyWeightPref1.setRequestFocusEnabled(false);
        bodyWeightPref1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyWeightPref1ActionPerformed(evt);
            }
        });

        hairColourPref5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        hairColourPref5.setText("Hair Colour 5");
        hairColourPref5.setPreferredSize(new java.awt.Dimension(100, 25));
        hairColourPref5.setRequestFocusEnabled(false);
        hairColourPref5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairColourPref5ActionPerformed(evt);
            }
        });

        bodyWeightPref3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bodyWeightPref3.setText("Body Weight 3");
        bodyWeightPref3.setPreferredSize(new java.awt.Dimension(100, 25));
        bodyWeightPref3.setRequestFocusEnabled(false);
        bodyWeightPref3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyWeightPref3ActionPerformed(evt);
            }
        });

        HeightPref1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        HeightPref1.setText("Height 1");
        HeightPref1.setPreferredSize(new java.awt.Dimension(100, 25));
        HeightPref1.setRequestFocusEnabled(false);
        HeightPref1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightPref1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Personal");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Prefered");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(549, 549, 549)
                        .addComponent(Finished)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(HeightPersonal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(HeightPersonal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(HeightPersonal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(HeightPersonal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(HeightPersonal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bodyTypePersonal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bodyTypePersonal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bodyTypePersonal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bodyTypePersonal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bodyTypePersonal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(hairColourPersonal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hairColourPersonal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hairColourPersonal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hairColourPersonal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hairColourPersonal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(backgroundPersonal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(backgroundPersonal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(backgroundPersonal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(backgroundPersonal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(backgroundPersonal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(bodyWeightPersonal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bodyWeightPersonal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bodyWeightPersonal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bodyWeightPersonal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bodyWeightPersonal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel7))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HeightPref1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HeightPref2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HeightPref3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HeightPref4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HeightPref5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(bodyTypePref1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bodyTypePref2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bodyTypePref3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bodyTypePref4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bodyTypePref5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(hairColourPref1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(hairColourPref2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(hairColourPref3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(hairColourPref4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(hairColourPref5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(backgroundPref1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(backgroundPref2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(backgroundPref3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(backgroundPref4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(backgroundPref5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bodyWeightPref1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bodyWeightPref2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bodyWeightPref3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bodyWeightPref4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bodyWeightPref5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel15)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodyTypePersonal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyTypePersonal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyTypePersonal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyTypePersonal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyTypePersonal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodyWeightPersonal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyWeightPersonal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyWeightPersonal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyWeightPersonal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyWeightPersonal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hairColourPersonal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hairColourPersonal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hairColourPersonal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hairColourPersonal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hairColourPersonal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backgroundPersonal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundPersonal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundPersonal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundPersonal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundPersonal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HeightPersonal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeightPersonal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeightPersonal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeightPersonal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeightPersonal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodyTypePref1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyTypePref2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyTypePref3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyTypePref4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyTypePref5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodyWeightPref1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyWeightPref2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyWeightPref3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyWeightPref4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyWeightPref5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hairColourPref2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hairColourPref3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hairColourPref4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hairColourPref5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hairColourPref1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backgroundPref1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundPref2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundPref3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundPref4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundPref5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HeightPref1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeightPref2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeightPref3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeightPref4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeightPref5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(37, 37, 37)
                .addComponent(Finished)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bodyTypePersonal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyTypePersonal1ActionPerformed
        bodyTypePersonal = 1;
        System.out.println("it works!!!");
    }//GEN-LAST:event_bodyTypePersonal1ActionPerformed

    private void bodyTypePersonal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyTypePersonal4ActionPerformed
        bodyTypePersonal = 4;
    }//GEN-LAST:event_bodyTypePersonal4ActionPerformed

    private void bodyTypePersonal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyTypePersonal2ActionPerformed
        bodyTypePersonal = 2;
    }//GEN-LAST:event_bodyTypePersonal2ActionPerformed

    private void bodyTypePersonal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyTypePersonal3ActionPerformed
        bodyTypePersonal = 3;
    }//GEN-LAST:event_bodyTypePersonal3ActionPerformed

    private void bodyTypePersonal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyTypePersonal5ActionPerformed
        bodyTypePersonal = 5;
    }//GEN-LAST:event_bodyTypePersonal5ActionPerformed

    private void HeightPersonal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightPersonal2ActionPerformed
        heightPersonal = 2;
    }//GEN-LAST:event_HeightPersonal2ActionPerformed

    private void HeightPersonal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightPersonal1ActionPerformed
        heightPersonal = 1;
    }//GEN-LAST:event_HeightPersonal1ActionPerformed

    private void HeightPersonal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightPersonal5ActionPerformed
        heightPersonal = 5;
    }//GEN-LAST:event_HeightPersonal5ActionPerformed

    private void HeightPersonal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightPersonal4ActionPerformed
        heightPersonal = 4;
    }//GEN-LAST:event_HeightPersonal4ActionPerformed

    private void HeightPersonal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightPersonal3ActionPerformed
        heightPersonal = 3;
    }//GEN-LAST:event_HeightPersonal3ActionPerformed

    private void hairColourPersonal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairColourPersonal5ActionPerformed
        hairColPersonal = 5;
    }//GEN-LAST:event_hairColourPersonal5ActionPerformed

    private void hairColourPersonal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairColourPersonal4ActionPerformed
        hairColPersonal = 4;
    }//GEN-LAST:event_hairColourPersonal4ActionPerformed

    private void hairColourPersonal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairColourPersonal2ActionPerformed
        hairColPersonal = 2;
    }//GEN-LAST:event_hairColourPersonal2ActionPerformed

    private void hairColourPersonal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairColourPersonal1ActionPerformed
        hairColPersonal = 1;
    }//GEN-LAST:event_hairColourPersonal1ActionPerformed

    private void hairColourPersonal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairColourPersonal3ActionPerformed
        hairColPersonal = 3;
    }//GEN-LAST:event_hairColourPersonal3ActionPerformed

    private void backgroundPersonal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundPersonal5ActionPerformed
       backgroundPersonal = 5;
    }//GEN-LAST:event_backgroundPersonal5ActionPerformed

    private void backgroundPersonal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundPersonal4ActionPerformed
      backgroundPersonal = 4;
    }//GEN-LAST:event_backgroundPersonal4ActionPerformed

    private void backgroundPersonal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundPersonal2ActionPerformed
    backgroundPersonal = 2;
    }//GEN-LAST:event_backgroundPersonal2ActionPerformed

    private void backgroundPersonal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundPersonal1ActionPerformed
     backgroundPersonal = 1;
    }//GEN-LAST:event_backgroundPersonal1ActionPerformed

    private void backgroundPersonal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundPersonal3ActionPerformed
     backgroundPersonal = 3;
    }//GEN-LAST:event_backgroundPersonal3ActionPerformed

    private void bodyWeightPersonal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyWeightPersonal5ActionPerformed
     bodyWeightPersonal = 5;
    }//GEN-LAST:event_bodyWeightPersonal5ActionPerformed

    private void bodyWeightPersonal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyWeightPersonal4ActionPerformed
      bodyWeightPersonal = 4;
    }//GEN-LAST:event_bodyWeightPersonal4ActionPerformed

    private void bodyWeightPersonal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyWeightPersonal2ActionPerformed
        bodyWeightPersonal = 2;
    }//GEN-LAST:event_bodyWeightPersonal2ActionPerformed

    private void bodyWeightPersonal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyWeightPersonal1ActionPerformed
       bodyWeightPersonal = 1;
    }//GEN-LAST:event_bodyWeightPersonal1ActionPerformed

    private void bodyWeightPersonal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyWeightPersonal3ActionPerformed
       bodyWeightPersonal = 3;
    }//GEN-LAST:event_bodyWeightPersonal3ActionPerformed

    private void FinishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishedActionPerformed
    String personalAppearanceInfo = (bodyTypePersonal + "," + bodyWeightPersonal +  "," + hairColPersonal + "," + backgroundPersonal + "," + heightPersonal);
    System.out.println(personalAppearanceInfo);
        //check the field for personality and looks are both numbers
       
        
       
    }//GEN-LAST:event_FinishedActionPerformed

    private void backgroundPref5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundPref5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundPref5ActionPerformed

    private void hairColourPref3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairColourPref3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hairColourPref3ActionPerformed

    private void hairColourPref1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairColourPref1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hairColourPref1ActionPerformed

    private void hairColourPref2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairColourPref2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hairColourPref2ActionPerformed

    private void hairColourPref4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairColourPref4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hairColourPref4ActionPerformed

    private void backgroundPref1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundPref1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundPref1ActionPerformed

    private void backgroundPref3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundPref3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundPref3ActionPerformed

    private void backgroundPref4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundPref4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundPref4ActionPerformed

    private void backgroundPref2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundPref2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundPref2ActionPerformed

    private void HeightPref2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightPref2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightPref2ActionPerformed

    private void bodyTypePref5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyTypePref5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodyTypePref5ActionPerformed

    private void bodyWeightPref5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyWeightPref5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodyWeightPref5ActionPerformed

    private void bodyTypePref2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyTypePref2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodyTypePref2ActionPerformed

    private void bodyTypePref1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyTypePref1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodyTypePref1ActionPerformed

    private void bodyTypePref4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyTypePref4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodyTypePref4ActionPerformed

    private void bodyTypePref3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyTypePref3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodyTypePref3ActionPerformed

    private void HeightPref5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightPref5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightPref5ActionPerformed

    private void bodyWeightPref4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyWeightPref4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodyWeightPref4ActionPerformed

    private void HeightPref4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightPref4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightPref4ActionPerformed

    private void bodyWeightPref2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyWeightPref2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodyWeightPref2ActionPerformed

    private void HeightPref3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightPref3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightPref3ActionPerformed

    private void bodyWeightPref1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyWeightPref1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodyWeightPref1ActionPerformed

    private void hairColourPref5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairColourPref5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hairColourPref5ActionPerformed

    private void bodyWeightPref3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyWeightPref3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodyWeightPref3ActionPerformed

    private void HeightPref1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightPref1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightPref1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppearanceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppearanceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppearanceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppearanceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppearanceQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Finished;
    private javax.swing.JButton HeightPersonal1;
    private javax.swing.JButton HeightPersonal2;
    private javax.swing.JButton HeightPersonal3;
    private javax.swing.JButton HeightPersonal4;
    private javax.swing.JButton HeightPersonal5;
    private javax.swing.JButton HeightPref1;
    private javax.swing.JButton HeightPref2;
    private javax.swing.JButton HeightPref3;
    private javax.swing.JButton HeightPref4;
    private javax.swing.JButton HeightPref5;
    private javax.swing.JButton backgroundPersonal1;
    private javax.swing.JButton backgroundPersonal2;
    private javax.swing.JButton backgroundPersonal3;
    private javax.swing.JButton backgroundPersonal4;
    private javax.swing.JButton backgroundPersonal5;
    private javax.swing.JButton backgroundPref1;
    private javax.swing.JButton backgroundPref2;
    private javax.swing.JButton backgroundPref3;
    private javax.swing.JButton backgroundPref4;
    private javax.swing.JButton backgroundPref5;
    private javax.swing.JButton bodyTypePersonal1;
    private javax.swing.JButton bodyTypePersonal2;
    private javax.swing.JButton bodyTypePersonal3;
    private javax.swing.JButton bodyTypePersonal4;
    private javax.swing.JButton bodyTypePersonal5;
    private javax.swing.JButton bodyTypePref1;
    private javax.swing.JButton bodyTypePref2;
    private javax.swing.JButton bodyTypePref3;
    private javax.swing.JButton bodyTypePref4;
    private javax.swing.JButton bodyTypePref5;
    private javax.swing.JButton bodyWeightPersonal1;
    private javax.swing.JButton bodyWeightPersonal2;
    private javax.swing.JButton bodyWeightPersonal3;
    private javax.swing.JButton bodyWeightPersonal4;
    private javax.swing.JButton bodyWeightPersonal5;
    private javax.swing.JButton bodyWeightPref1;
    private javax.swing.JButton bodyWeightPref2;
    private javax.swing.JButton bodyWeightPref3;
    private javax.swing.JButton bodyWeightPref4;
    private javax.swing.JButton bodyWeightPref5;
    private javax.swing.JButton hairColourPersonal1;
    private javax.swing.JButton hairColourPersonal2;
    private javax.swing.JButton hairColourPersonal3;
    private javax.swing.JButton hairColourPersonal4;
    private javax.swing.JButton hairColourPersonal5;
    private javax.swing.JButton hairColourPref1;
    private javax.swing.JButton hairColourPref2;
    private javax.swing.JButton hairColourPref3;
    private javax.swing.JButton hairColourPref4;
    private javax.swing.JButton hairColourPref5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}

