/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matchmakerfinal;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Stephanie
 */
public class General extends javax.swing.JFrame {

    public String gender;
    public String grade;
    public String LFGender = "";
    public String[] LFGrade = {"","","",""};
          
    /**
     * Creates new form General
     */
    public General() {
        initComponents();
          setSize(1108, 733);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        personality = new javax.swing.JTextField();
        looks = new javax.swing.JTextField();
        LFGrade9 = new javax.swing.JButton();
        LFGrade10 = new javax.swing.JButton();
        LFGrade11 = new javax.swing.JButton();
        LFGrade12 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        myGrade10 = new javax.swing.JButton();
        myGrade9 = new javax.swing.JButton();
        myGrade11 = new javax.swing.JButton();
        myGrade12 = new javax.swing.JButton();
        myGenderFemale = new javax.swing.JButton();
        myGenderMale = new javax.swing.JButton();
        LFFemale = new javax.swing.JButton();
        LFMale = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        firstName.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        getContentPane().add(firstName);
        firstName.setBounds(310, 240, 200, 40);

        lastName.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        getContentPane().add(lastName);
        lastName.setBounds(740, 240, 210, 40);

        personality.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        getContentPane().add(personality);
        personality.setBounds(700, 440, 80, 40);

        looks.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        getContentPane().add(looks);
        looks.setBounds(440, 440, 80, 40);

        LFGrade9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LFGrade9ActionPerformed(evt);
            }
        });
        getContentPane().add(LFGrade9);
        LFGrade9.setBounds(610, 610, 40, 30);

        LFGrade10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LFGrade10ActionPerformed(evt);
            }
        });
        getContentPane().add(LFGrade10);
        LFGrade10.setBounds(680, 610, 40, 30);

        LFGrade11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LFGrade11ActionPerformed(evt);
            }
        });
        getContentPane().add(LFGrade11);
        LFGrade11.setBounds(740, 610, 40, 30);

        LFGrade12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LFGrade12ActionPerformed(evt);
            }
        });
        getContentPane().add(LFGrade12);
        LFGrade12.setBounds(810, 610, 40, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("~ Finished ~");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(970, 650, 120, 70);

        myGrade10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myGrade10ActionPerformed(evt);
            }
        });
        getContentPane().add(myGrade10);
        myGrade10.setBounds(790, 330, 40, 30);

        myGrade9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myGrade9ActionPerformed(evt);
            }
        });
        getContentPane().add(myGrade9);
        myGrade9.setBounds(730, 330, 40, 30);

        myGrade11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myGrade11ActionPerformed(evt);
            }
        });
        getContentPane().add(myGrade11);
        myGrade11.setBounds(860, 330, 40, 30);

        myGrade12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myGrade12ActionPerformed(evt);
            }
        });
        getContentPane().add(myGrade12);
        myGrade12.setBounds(920, 330, 40, 30);

        myGenderFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myGenderFemaleActionPerformed(evt);
            }
        });
        getContentPane().add(myGenderFemale);
        myGenderFemale.setBounds(310, 330, 40, 30);

        myGenderMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myGenderMaleActionPerformed(evt);
            }
        });
        getContentPane().add(myGenderMale);
        myGenderMale.setBounds(410, 330, 40, 30);

        LFFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LFFemaleActionPerformed(evt);
            }
        });
        getContentPane().add(LFFemale);
        LFFemale.setBounds(310, 603, 40, 30);

        LFMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LFMaleActionPerformed(evt);
            }
        });
        getContentPane().add(LFMale);
        LFMale.setBounds(400, 600, 40, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchmakerfinal/General.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1110, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (checkNames(firstName) && checkNames(lastName)){
             JOptionPane.showMessageDialog(this, "Please ensure the name fields are filled in correctly", "Names", JOptionPane.PLAIN_MESSAGE);
        }
        //check the field for personality and looks are both numbers
        else if (checkRatio(personality) && checkRatio(looks)){
            JOptionPane.showMessageDialog(this, "Please ensure the looks:personality field contain only numbers", "Names", JOptionPane.PLAIN_MESSAGE);
        }
        else if (addTo()){
         JOptionPane.showMessageDialog(this, "Please ensure the looks:personality field add to 100%", "% Looks to Personality", JOptionPane.PLAIN_MESSAGE);   
        }
       
        else if (checkGrade(LFGrade[0]) && checkGrade(LFGrade[1]) && checkGrade(LFGrade[2]) && checkGrade(LFGrade[3])){
         JOptionPane.showMessageDialog(this, "Please select one or more grade preferences", "Looking for Grade..", JOptionPane.PLAIN_MESSAGE);      
            
        }
        else if (empty(LFGender)){
         JOptionPane.showMessageDialog(this, "Please select one or more gender preferences", "Looking for Gender..", JOptionPane.PLAIN_MESSAGE);         
        }
        else{
            String gradeInterest = "";
            for (int i = 0; i < 3; i ++){
                if ("".equals(LFGrade[i])){
                    
                }
                else {
                     gradeInterest = gradeInterest + LFGrade[i] +",";
                }
            }     
          int length =   gradeInterest.length();
        gradeInterest = gradeInterest + LFGrade[3];
        if (gradeInterest.charAt(length) == ','){
            gradeInterest = gradeInterest.substring(0,(length - 1));
        }
        // store information in String
        String userInfo = (firstName.getText()+ "," + lastName.getText()+ "," + gender + "," + grade + "," + personality.getText()+ "," + LFGender + "," + gradeInterest);
        System.out.println(userInfo);
        setVisible(false);
        new Menu().setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    private boolean addTo(){
    int RP = Integer.parseInt(personality.getText());
    int LP = Integer.parseInt(looks.getText());
    if (LP + RP == 100){
        return false;
    }
    return true;
    
}
    private boolean checkGrade (String grade){
        if (grade == ""){
        return true;
    }
        return false;
    }
    private boolean checkRatio (JTextField ratio){
      
        return !ratio.getText().matches("[0-9]+");        
    }
    
    private boolean checkNames(JTextField name){
        //This method will check each the name inputs and return true if they are not filled in properly
       // is the name filled in?
        if (empty(name.getText())){
            return true;
        }
        //is the content only letters?
        else if (letters(name.getText())){
            return true;
        }
        return false;
    }
    public boolean letters(String name) {
    char[] chars = name.toCharArray();

    for (char c : chars) {
        if(!Character.isLetter(c)) {
            return true;
        }
    }

    return false;
}

        private boolean empty(String text) {
        // if the field is empty
        if (text.isEmpty()) {
            // return true (yes it is empty)
            
            return true;
        }
        // if the field is not empty return false
        return false;

    }
    
    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void myGenderFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myGenderFemaleActionPerformed
       gender = "female";
    }//GEN-LAST:event_myGenderFemaleActionPerformed

    private void myGenderMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myGenderMaleActionPerformed
       gender = "male";
    }//GEN-LAST:event_myGenderMaleActionPerformed

    private void myGrade9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myGrade9ActionPerformed
       grade = "9";
    }//GEN-LAST:event_myGrade9ActionPerformed

    private void myGrade10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myGrade10ActionPerformed
       grade = "10";
    }//GEN-LAST:event_myGrade10ActionPerformed

    private void myGrade11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myGrade11ActionPerformed
     grade = "11";
    }//GEN-LAST:event_myGrade11ActionPerformed

    private void myGrade12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myGrade12ActionPerformed
      grade = "12";
    }//GEN-LAST:event_myGrade12ActionPerformed

    private void LFFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LFFemaleActionPerformed
        if ("male".equals(LFGender)){
            LFGender = "female,male";
        }
        else if ("".equals(LFGender)){
            LFGender = "female";
        }
        else if ("female,male".equals(LFGender)){
            LFGender = "male";
        }
        else {
            LFGender = "";
        }
    }//GEN-LAST:event_LFFemaleActionPerformed

    private void LFMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LFMaleActionPerformed
       if ("male".equals(LFGender)){
            LFGender = "";
        }
        else if ("".equals(LFGender)){
            LFGender = "male";
        }
        else if ("female,male".equals(LFGender)){
            LFGender = "female";
        }
        else {
            LFGender = "female,male";
        }
    
    }//GEN-LAST:event_LFMaleActionPerformed

    private void LFGrade9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LFGrade9ActionPerformed
        if ("9".equals(LFGrade[0])){
            LFGrade[0] = "";
        }
        else {
            LFGrade[0] = "9";
        }
    }//GEN-LAST:event_LFGrade9ActionPerformed

    private void LFGrade10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LFGrade10ActionPerformed
         if ("10".equals(LFGrade[1])){
               LFGrade[1] = "";
           
        }
        else {
               LFGrade[1] = "10";
           
        }
           
    }//GEN-LAST:event_LFGrade10ActionPerformed

    private void LFGrade11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LFGrade11ActionPerformed
      if ("11".equals(LFGrade[2])){
            LFGrade[2] = "";
           
        }
        else {
            LFGrade[2] = "11";
            
        }
          
    }//GEN-LAST:event_LFGrade11ActionPerformed

    private void LFGrade12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LFGrade12ActionPerformed
        if ("12".equals(LFGrade[3])){
              LFGrade[3] = "";
            
        }
        else {
              LFGrade[3] = "12";
       
        }
          
    }//GEN-LAST:event_LFGrade12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new General().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton LFFemale;
    private javax.swing.JButton LFGrade10;
    private javax.swing.JButton LFGrade11;
    private javax.swing.JButton LFGrade12;
    private javax.swing.JButton LFGrade9;
    private javax.swing.JButton LFMale;
    private javax.swing.JTextField firstName;
    private javax.swing.JButton jButton5;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField looks;
    private javax.swing.JButton myGenderFemale;
    private javax.swing.JButton myGenderMale;
    private javax.swing.JButton myGrade10;
    private javax.swing.JButton myGrade11;
    private javax.swing.JButton myGrade12;
    private javax.swing.JButton myGrade9;
    private javax.swing.JTextField personality;
    // End of variables declaration//GEN-END:variables
}
