/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matchmakerfinal;

/**
 *
 * @author Stephanie
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setSize(1100, 950);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genInfoQuiz = new javax.swing.JButton();
        looksQuiz = new javax.swing.JButton();
        personalityQuiz = new javax.swing.JButton();
        calculate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        genInfoQuiz.setText("Take Quiz");
        genInfoQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genInfoQuizActionPerformed(evt);
            }
        });
        getContentPane().add(genInfoQuiz);
        genInfoQuiz.setBounds(540, 250, 160, 30);

        looksQuiz.setText("Take Quiz");
        getContentPane().add(looksQuiz);
        looksQuiz.setBounds(550, 350, 150, 40);

        personalityQuiz.setText("Take Quiz");
        getContentPane().add(personalityQuiz);
        personalityQuiz.setBounds(550, 450, 150, 30);

        calculate.setText("Calculate!");
        getContentPane().add(calculate);
        calculate.setBounds(900, 560, 110, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchmakerfinal/Menu.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1110, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genInfoQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genInfoQuizActionPerformed
        setVisible(false);
        new General().setVisible(true);
    }//GEN-LAST:event_genInfoQuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JButton genInfoQuiz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton looksQuiz;
    private javax.swing.JButton personalityQuiz;
    // End of variables declaration//GEN-END:variables
}
